<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>netstandard2.1</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<LangVersion>latest</LangVersion>
		<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
		<GeneratePackageOnBuild Condition=" $(Configuration) == 'Release' ">true</GeneratePackageOnBuild>
		<GenerateDocumentationFile Condition=" $(Configuration) == 'Release' ">True</GenerateDocumentationFile>
		<PackageId>FFmpegDotNet.Skia</PackageId>
		<Title>FFmpeg.Skia</Title>
		<Authors>Pascal Krenckel</Authors>
		<Description>
			Provides SkiaSharp integration for the FFmpeg .NET wrapper.
			Enables converting FFmpeg AVFrames to SKImage or SKBitmap, and includes high-level classes (FFCodec2Skia, SKVideo) for decoding and rendering videos or images with Skia.
		</Description>
		<Copyright>Copyright (c) 2025 Pascal Krenckel. All rights reserved.</Copyright>
		<PackageProjectUrl>https://github.com/Pascal-Krenckel/FFmpeg.Skia</PackageProjectUrl>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/Pascal-Krenckel/FFmpeg.Skia</RepositoryUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<IncludeSymbols>True</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<RepositoryType>git</RepositoryType>
		<PackageTags>ffmpeg; skia</PackageTags>
		<PackageLicenseFile>LICENSE.txt</PackageLicenseFile>
		<Version>2.3.0</Version>
		<PackageReleaseNotes>
			=== 2.3.0 ===
			Added SKAnimatedImage - a class that allows for both automatic and manual decoding auf image/video data.
			=== 2.2.0 ===
			AVFrame.CopyTo(SKBitmap) allows now empty bitmaps.
			SKBitmap.Reference(AVFrame). Same as AVFrame.AsSKBitmap(), just with an existing SKBitmap.
			=== 2.1.0 ===
			Added CopyTo-Extension that copies the content of SKBitmap/SKImage into an existing AVFrame
			BugFix: Removed blocking scheduler from SKVideo
			=== 2.0.0 ===
			Some smaller BugFixes
			Added xml docu into the package.
			Some functions got renamed.
	    </PackageReleaseNotes>
		<GenerateDocumentationFile>True</GenerateDocumentationFile>
	</PropertyGroup>

	<ItemGroup>
		<None Include="..\LICENSE.txt">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Include="..\README.md">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="FFmpegDotNet" Version="8.1.2.11" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.400">
		  <PrivateAssets>all</PrivateAssets>
		  <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="SkiaSharp" Version="4.151.1" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="SkiaSharp" />
	</ItemGroup>

</Project>
